In [1]:
import sklearn

In [2]:
import pandas as pd

In [6]:
pd_data = pd.read_csv('./files/newyork_taxi.csv')

In [7]:
pd_data.head()

id  vendor_id      pickup_datetime     dropoff_datetime  \
0  id2875421          2  2016-03-14 17:24:55  2016-03-14 17:32:30   
1  id2377394          1  2016-06-12 00:43:35  2016-06-12 00:54:38   
2  id3858529          2  2016-01-19 11:35:24  2016-01-19 12:10:48   
3  id3504673          2  2016-04-06 19:32:31  2016-04-06 19:39:40   
4  id2181028          2  2016-03-26 13:30:55  2016-03-26 13:38:10   

   passenger_count  pickup_longitude  pickup_latitude  dropoff_longitude  \
0                1        -73.982155        40.767937         -73.964630   
1                1        -73.980415        40.738564         -73.999481   
2                1        -73.979027        40.763939         -74.005333   
3                1        -74.010040        40.719971         -74.012268   
4                1        -73.973053        40.793209         -73.972923   

   dropoff_latitude store_and_fwd_flag  trip_duration  
0         40.765602                  N            455  
1         40.731152                  N            663  
2         40.710087                  N           2124  
3         40.706718                  N            429  
4         40.782520                  N            435

In [9]:
pd_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1458644 entries, 0 to 1458643
Data columns (total 11 columns):
 #   Column              Non-Null Count    Dtype  
---  ------              --------------    -----  
 0   id                  1458644 non-null  object 
 1   vendor_id           1458644 non-null  int64  
 2   pickup_datetime     1458644 non-null  object 
 3   dropoff_datetime    1458644 non-null  object 
 4   passenger_count     1458644 non-null  int64  
 5   pickup_longitude    1458644 non-null  float64
 6   pickup_latitude     1458644 non-null  float64
 7   dropoff_longitude   1458644 non-null  float64
 8   dropoff_latitude    1458644 non-null  float64
 9   store_and_fwd_flag  1458644 non-null  object 
 10  trip_duration       1458644 non-null  int64  
dtypes: float64(4), int64(3), object(4)
memory usage: 122.4+ MB


In [ ]:
data2['dif_longitude'] = np.abs(data2['pickup_longitude'] - data2['dropoff_longitude'])

In [ ]:
data2['dif_latitude'] = np.abs(data2['pickup_latitude'] - data2['dropoff_latitude'])

In [ ]:
data2['dist'] = np.sqrt(np.power(data2['dif_longitude'],2) + np.power(data2['dif_latitude'],2))

In [10]:
x = pd_data[['passenger_count']]

In [11]:
y = pd_data[['trip_duration']]

In [12]:
x.shape, y.shape

((1458644, 1), (1458644, 1))

In [13]:
pd_data[['passenger_count','trip_duration']]

passenger_count  trip_duration
0                      1            455
1                      1            663
2                      1           2124
3                      1            429
4                      1            435
...                  ...            ...
1458639                4            778
1458640                1            655
1458641                1            764
1458642                1            373
1458643                1            198

[1458644 rows x 2 columns]

In [14]:
from sklearn.model_selection import train_test_split

In [15]:
X_train, X_test, Y_train, Y_test = train_test_split(x, y)
X_train.shape, X_test.shape, Y_train.shape, Y_test.shape

((1093983, 1), (364661, 1), (1093983, 1), (364661, 1))

In [16]:
from sklearn.linear_model import LinearRegression

In [17]:
lr = LinearRegression()

In [18]:
# lr.fit(x,y)
lr.fit(X_train, Y_train)

LinearRegression()

In [19]:
lr.coef_, lr.intercept_ # 기울기coef_ 여기서 coef가 2개

(array([[32.69352241]]), array([908.29321473]))

In [20]:
# check with total data
lr.score(x, y)

7.13082333423376e-05

In [21]:
# check with apart train data
lr.score(X_train, Y_train)

5.55639011411424e-05

In [22]:
# check with apart test data
lr.score(X_test, Y_test)

0.00021896580263869314

In [23]:
lr.predict([[1]])

array([[940.98673714]])

In [24]:
lr.predict([[6]])

array([[1104.45434921]])

우리가 알고 있는 유클리디안 공간으로 산정하면 혼남...ㅠㅠㅠ

위도 경도는 약간 다르다...!