In [1]:
from sklearn import datasets

In [2]:
iris = datasets.load_iris()
type(iris)

sklearn.utils.Bunch

In [3]:
iris

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [4]:
x = iris.data
y = iris.target
x.shape, y.shape, type(x), type(y)

((150, 4), (150,), numpy.ndarray, numpy.ndarray)

In [5]:
import numpy as np

In [6]:
np.unique(y)

array([0, 1, 2])

In [7]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y)
x_train.shape, y_train.shape, x_test.shape, y_test.shape

((112, 4), (112,), (38, 4), (38,))

In [8]:
from sklearn.linear_model import LogisticRegression
log = LogisticRegression()

In [9]:
log.fit(x_train, y_train)

LogisticRegression()

In [11]:
log.coef_, log.intercept_

(array([[-0.41024064,  0.90836391, -2.31962145, -1.00012511],
        [ 0.38619424, -0.30067449, -0.10789083, -0.80624561],
        [ 0.0240464 , -0.60768942,  2.42751228,  1.80637073]]),
 array([  9.05623254,   2.33130173, -11.38753427]))

-0.41024064,  0.90836391, -2.31962145, -1.00012511 +9.05623254

In [16]:
log.predict_proba(x_train[100:104])

array([[9.42461486e-01, 5.75375164e-02, 9.97749256e-07],
       [9.71838913e-01, 2.81609800e-02, 1.06557664e-07],
       [7.43124433e-05, 1.18328687e-01, 8.81597000e-01],
       [9.50803500e-01, 4.91961506e-02, 3.49170643e-07]])

#### y = 9.42461486e-01 x_1 + 5.75375164e-02 x_2 + 9.97749256e-07 x_3 + 9.50803500e-01
#### y = 9.71838913e-01 x_1 + 2.81609800e-02 x_2 + 1.06557664e-07 x_3 + 4.91961506e-02
#### y = 7.43124433e-05 x_1 + 1.18328687e-01 x_2 + 8.81597000e-01 x_3 + 3.49170643e-07

In [14]:
log.predict(x_train[100:104])

array([0, 0, 2, 0])

In [15]:
9.42461486e-01 + 5.75375164e-02 + 9.97749256e-07 # 더해서 1이 나오는지 확인.

1.0000000001492562

## 평가부분

In [17]:
from sklearn import metrics # 메트릭 안에는 여러가지 평가하룻 있는 자료가 있음.

##### 선형휘귀 :원래 Y의 값과 프리딕트의 Y값과 빼서 편차를 구하고 더함.
##### 예측한 데이터 편차로 판별함.

In [20]:
y_pred=log.predict(x_train)
y_pred.shape, y_train.shape

((112,), (112,))

In [21]:
y_pred


array([0, 2, 0, 2, 1, 2, 0, 1, 0, 0, 1, 2, 0, 1, 2, 0, 2, 2, 1, 1, 0, 1,
       1, 2, 0, 0, 2, 2, 2, 1, 2, 1, 2, 0, 1, 1, 2, 1, 0, 1, 1, 0, 0, 0,
       1, 1, 0, 1, 0, 0, 2, 2, 1, 1, 1, 2, 1, 0, 2, 2, 2, 1, 1, 0, 0, 2,
       2, 0, 0, 2, 1, 1, 1, 0, 0, 1, 2, 2, 0, 1, 1, 1, 2, 2, 2, 1, 0, 1,
       2, 0, 2, 2, 0, 1, 1, 0, 2, 2, 2, 0, 0, 0, 2, 0, 2, 2, 0, 0, 1, 1,
       0, 0])

In [23]:
y_train


array([0, 1, 0, 2, 1, 1, 0, 1, 0, 0, 1, 2, 0, 1, 2, 0, 2, 2, 1, 1, 0, 1,
       1, 2, 0, 0, 2, 2, 2, 1, 2, 1, 2, 0, 1, 1, 2, 1, 0, 1, 1, 0, 0, 0,
       1, 1, 0, 1, 0, 0, 2, 2, 1, 1, 1, 2, 1, 0, 2, 2, 2, 1, 1, 0, 0, 2,
       2, 0, 0, 1, 1, 1, 1, 0, 0, 1, 2, 2, 0, 1, 1, 1, 2, 2, 2, 1, 0, 1,
       2, 0, 2, 2, 0, 2, 1, 0, 2, 2, 2, 0, 0, 0, 2, 0, 2, 2, 0, 0, 1, 1,
       0, 0])

In [24]:
print(metrics.classification_report(y_train, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        38
           1       0.97      0.92      0.95        39
           2       0.92      0.97      0.94        35

    accuracy                           0.96       112
   macro avg       0.96      0.96      0.96       112
weighted avg       0.97      0.96      0.96       112

